services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: '${TZ}'             # Set timezone using .env file
      WEBPASSWORD: '${WEBPASSWORD}'  # Inject password from .env
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'  # Only required if using Pi-hole's DHCP
      - '80:80/tcp'
      - '443:443/tcp'
    dns:
      - 127.0.0.1      # Pi-hole DNS resolver for itself
      - 8.8.8.8        # Upstream DNS server (Google DNS)
    cap_add:
      - NET_ADMIN      # Required for Pi-hole to manage network settings
    restart: unless-stopped
  openvpn-client:
    image: kylemanna/openvpn
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    volumes:
      - ./ovpn-config:/etc/openvpn  # Adjust the path to where your .ovpn config files are stored
    environment:
      - OVPN_CONFIG=config-file.ovpn  # Replace with your actual .ovpn filename
    restart: unless-stopped
